language: node_js
node_js:
  - lts/*
  - node

before_script:
  - make --output-sync --jobs data

script:
  - make --output-sync --jobs test lint build
  - bundlewatch

after_success:
  - make --output-sync --jobs ci

notifications:
  webhooks:
    - https://coveralls.io/webhook
    - https://www.travisbuddy.com/
