language: node_js
node_js:
  - lts/*
  - node

before_script:
  - make --jobs --output-sync prerequisites

script:
  - npm test -- --coverage
  - make build

after_success:
  - codecov --disable=gcov
  - ls -lAh bundle/*
  - bundlewatch
