language: node_js
node_js:
  - lts/*
  - node

before_script:
  - make --jobs --output-sync prerequisites

script:
  - npm test -- --coverage
  - make --jobs build

after_success:
  - npm run codecov
  - ls -lAh bundle/*
