language: node_js
node_js:
  - lts/*
  - node

before_script:
  - make --output-sync --jobs prerequisites

script:
  - make --output-sync --jobs test lint build
  - bundlewatch

after_success:
  - codecov --disable=gcov
  - npm outdated
  - ls -lAh bundle/*

notifications:
  webhooks: https://www.travisbuddy.com/
