---
name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Linting the codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node_modules
        run: make --jobs node_modules

      - name: Run ESLint / Prettier
        run: make --output-sync --jobs lint
